/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        serif: ['"Libre Caslon Text"', 'Georgia', 'serif'],
        sans: ['"Work Sans"', 'system-ui', 'sans-serif'],
      },
      colors: {
        background: '#fff8f8',
        'on-background': '#22191c',
        surface: {
          DEFAULT: '#fff8f8',
          dim: '#e7d6d9',
          bright: '#fff8f8',
          'container-lowest': '#ffffff',
          'container-low': '#fff0f3',
          container: '#fbeaed',
          'container-high': '#f5e4e8',
          'container-highest': '#efdee2',
          variant: '#efdee2',
          tint: '#6b5a60',
        },
        'on-surface': '#22191c',
        'on-surface-variant': '#4d4447',
        primary: {
          DEFAULT: '#6b5a60',
          container: '#fce4ec',
          fixed: '#f4dce4',
          'fixed-dim': '#d7c1c8',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#76646b',
        secondary: {
          DEFAULT: '#665c5e',
          container: '#ebdcdf',
          fixed: '#eddfe2',
          'fixed-dim': '#d1c3c6',
        },
        tertiary: {
          DEFAULT: '#ab2c5d',
          container: '#ffe3e8',
          fixed: '#ffd9e1',
          'fixed-dim': '#ffb1c5',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b93768',
        outline: {
          DEFAULT: '#7f7478',
          variant: '#d0c3c7',
        },
        'inverse-surface': '#382e31',
        'inverse-on-surface': '#feecf0',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      spacing: {
        'base': '8px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'card': '0 8px 32px rgba(74, 63, 66, 0.06)',
        'card-hover': '0 12px 40px rgba(74, 63, 66, 0.1)',
        'soft': '0 4px 16px rgba(74, 63, 66, 0.03)',
      },
    },
  },
  plugins: [],
}
