// Mock data for development / demo (no Supabase connection needed)
import type { DimCaregiver, CareCategoryType } from './types/database'

export const MOCK_CAREGIVERS: DimCaregiver[] = [
  // Strefa A – Senior i Rehabilitacja
  {
    id: '1',
    nazwa: 'Anna Kowalska',
    profesja: 'fizjoterapeuta',
    weryfikacja_pwz: true,
    miasto: 'Warszawa',
    stawka_godzinowa: 120,
    gotowosc_dojazdu: 25,
    bio: 'Specjalistka rehabilitacji poudarowej i geriatrycznej. Certyfikat NDT-Bobath. Pracuję z pacjentami po udarach, z chorobą Parkinsona i po endoprotezach.',
    lata_doswiadczenia: 8,
    telefon: '+48 501 100 001',
    email: 'a.kowalska@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    nazwa: 'Marek Wiśniewski',
    profesja: 'fizjoterapeuta',
    weryfikacja_pwz: true,
    miasto: 'Kraków',
    stawka_godzinowa: 110,
    gotowosc_dojazdu: 30,
    bio: 'Doświadczenie w rehabilitacji ortopedycznej i neurologicznej seniorów. Specjalizacja w ćwiczeniach równowagi i prewencji upadków.',
    lata_doswiadczenia: 12,
    telefon: '+48 501 100 002',
    email: 'm.wisniewski@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    nazwa: 'Beata Nowak',
    profesja: 'opiekunka_medyczna',
    weryfikacja_pwz: false,
    miasto: 'Warszawa',
    stawka_godzinowa: 65,
    gotowosc_dojazdu: 15,
    bio: 'Opieka całodobowa i dzienna nad osobami starszymi i po operacjach. Doświadczenie w opiece paliatywnej.',
    lata_doswiadczenia: 5,
    telefon: '+48 501 100 003',
    email: 'b.nowak@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    nazwa: 'Zofia Adamczyk',
    profesja: 'opiekunka_medyczna',
    weryfikacja_pwz: true,
    miasto: 'Wrocław',
    stawka_godzinowa: 75,
    gotowosc_dojazdu: 20,
    bio: 'Certyfikowana opiekunka osób starszych. Doświadczenie w chorobach neurodegeneracyjnych (Alzheimer, Parkinson).',
    lata_doswiadczenia: 9,
    telefon: '+48 501 100 004',
    email: 'z.adamczyk@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  // Strefa B – Mama i Dziecko
  {
    id: '5',
    nazwa: 'Katarzyna Lewandowska',
    profesja: 'polozna',
    weryfikacja_pwz: true,
    miasto: 'Warszawa',
    stawka_godzinowa: 150,
    gotowosc_dojazdu: 20,
    bio: 'Położna środowiskowa. Wizyty w domu, nauka karmienia piersią, opieka nad noworodkiem. Szkoła rodzenia.',
    lata_doswiadczenia: 10,
    telefon: '+48 501 200 001',
    email: 'k.lewandowska@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    nazwa: 'Monika Zielińska',
    profesja: 'polozna',
    weryfikacja_pwz: true,
    miasto: 'Gdańsk',
    stawka_godzinowa: 140,
    gotowosc_dojazdu: 25,
    bio: 'Specjalistka opieki okołoporodowej. Szkoła rodzenia online i stacjonarnie. Wsparcie po porodzie.',
    lata_doswiadczenia: 7,
    telefon: '+48 501 200 002',
    email: 'm.zielinska@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    nazwa: 'Ewa Piotrowska',
    profesja: 'dietetyk',
    weryfikacja_pwz: false,
    miasto: 'Kraków',
    stawka_godzinowa: 100,
    gotowosc_dojazdu: 15,
    bio: 'Dietetyk perinatalny. Diety ciążowe, laktacyjne i dla niemowląt. Konsultacje w domu lub online.',
    lata_doswiadczenia: 4,
    telefon: '+48 501 200 003',
    email: 'e.piotrowska@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    nazwa: 'Agnieszka Kamińska',
    profesja: 'dietetyk',
    weryfikacja_pwz: true,
    miasto: 'Poznań',
    stawka_godzinowa: 110,
    gotowosc_dojazdu: 20,
    bio: 'Certyfikat dietetyki klinicznej. Specjalizacja: alergie pokarmowe u dzieci, diety laktacyjne.',
    lata_doswiadczenia: 6,
    telefon: '+48 501 200 004',
    email: 'a.kaminska@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  // Strefa C – Zdrowie i Interwencje
  {
    id: '9',
    nazwa: 'Tomasz Jankowski',
    profesja: 'pielegniarka',
    weryfikacja_pwz: true,
    miasto: 'Warszawa',
    stawka_godzinowa: 90,
    gotowosc_dojazdu: 30,
    bio: 'Pielęgniarz opieki domowej. Iniekcje, opatrunki, pobieranie krwi, monitorowanie ciśnienia i cukru.',
    lata_doswiadczenia: 11,
    telefon: '+48 501 300 001',
    email: 't.jankowski@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '10',
    nazwa: 'Sylwia Wróbel',
    profesja: 'pielegniarka',
    weryfikacja_pwz: true,
    miasto: 'Łódź',
    stawka_godzinowa: 85,
    gotowosc_dojazdu: 25,
    bio: 'Specjalistka pielęgniarstwa internistycznego. Opieka nad chorymi przewlekle. Edukacja pacjenta.',
    lata_doswiadczenia: 8,
    telefon: '+48 501 300 002',
    email: 's.wrobel@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '11',
    nazwa: 'Rafał Mazur',
    profesja: 'ratownik_medyczny',
    weryfikacja_pwz: true,
    miasto: 'Warszawa',
    stawka_godzinowa: 130,
    gotowosc_dojazdu: 40,
    bio: 'Ratownik medyczny z doświadczeniem w SOR. Szkolenia pierwszej pomocy. Wizyty profilaktyczne.',
    lata_doswiadczenia: 6,
    telefon: '+48 501 300 003',
    email: 'r.mazur@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '12',
    nazwa: 'Paweł Krawczyk',
    profesja: 'ratownik_medyczny',
    weryfikacja_pwz: true,
    miasto: 'Wrocław',
    stawka_godzinowa: 120,
    gotowosc_dojazdu: 35,
    bio: 'Certyfikowany ratownik. Wizyty interwencyjne i profilaktyczne w domu. EKG, saturacja, ciśnienie.',
    lata_doswiadczenia: 9,
    telefon: '+48 501 300 004',
    email: 'p.krawczyk@example.com',
    created_at: '2024-01-01T00:00:00Z',
  },
]

export const CAREGIVERS_BY_CATEGORY: Record<CareCategoryType, DimCaregiver[]> = {
  senior_i_rehabilitacja: MOCK_CAREGIVERS.filter(c =>
    ['fizjoterapeuta', 'opiekunka_medyczna'].includes(c.profesja)
  ),
  mama_i_dziecko: MOCK_CAREGIVERS.filter(c =>
    ['polozna', 'dietetyk'].includes(c.profesja)
  ),
  zdrowie_i_interwencje: MOCK_CAREGIVERS.filter(c =>
    ['pielegniarka', 'ratownik_medyczny'].includes(c.profesja)
  ),
}

export const PROFESSION_LABELS: Record<string, string> = {
  fizjoterapeuta: 'Fizjoterapeuta',
  pielegniarka: 'Pielęgniarka/Pielęgniarz',
  opiekunka_medyczna: 'Opiekunka medyczna',
  polozna: 'Położna',
  ratownik_medyczny: 'Ratownik medyczny',
  dietetyk: 'Dietetyk',
}
